User.create!(email: "admin@gmail.com", password: "zxczxc", admin: true)
Category.create!(name: "Arts & Photography")
Category.create!(name: "Biographies & Memoirs")
Category.create!(name: "Business & Money")
Category.create!(name: "Calendars")
Category.create!(name: "Children's Books")
Category.create!(name: "Christian Books & Bibles")
Category.create!(name: "Comics & Graphic Novels")
Category.create!(name: "Computers & Technology")
Category.create!(name: "Cookbooks, Food & Wine")
Category.create!(name: "Crafts, Hobbies & Home")
Category.create!(name: "Education & Teaching")
Category.create!(name: "Engineering & Transportation")
Category.create!(name: "Gay & Lesbian")
Category.create!(name: "Health, Fitness & Dieting")
Category.create!(name: "History")
Category.create!(name: "Humor & Entertainment")
Category.create!(name: "Law")
Category.create!(name: "Literature & Fiction")
Category.create!(name: "Medical Books")
Category.create!(name: "Mystery, Thriller & Suspense")
Category.create!(name: "Parenting & Relationships")
Category.create!(name: "Politics & Social Sciences")
Category.create!(name: "Reference")
Category.create!(name: "Religion & Spirituality")
Category.create!(name: "Romance")
Category.create!(name: "Science & Math")
Category.create!(name: "Science Fiction & Fantasy")
Category.create!(name: "Self-Help")
Category.create!(name: "Sports & Outdoors")
Category.create!(name: "Teen & Young Adult")
Category.create!(name: "Test Preparation")
Category.create!(name: "Travel")
